### ISSUE TITLE
Problem with ember-in-viewport

### ISSUE THREAD

**Issue by mabab** [ember-infinity/ember-infinity#446]
ERROR Summary:

  - broccoliBuilderErrorStack: Error: ember-in-viewport and ember-in-viewport are using different versions of intersection-observer-admin (0.2.13 located at /usr/src/fe/node_modules/ember-infinity/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js vs 0.3.0 located at /usr/src/fe/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js)
    at Splitter.<anonymous> (/usr/src/fe/node_modules/ember-auto-import/js/splitter.js:172:23)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/usr/src/fe/node_modules/ember-auto-import/js/splitter.js:5:58)

  - code: [undefined]
  - codeFrame: ember-in-viewport and ember-in-viewport are using different versions of intersection-observer-admin (0.2.13 located at /usr/src/fe/node_modules/ember-infinity/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js vs 0.3.0 located at /usr/src/fe/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js)
  - errorMessage: ember-in-viewport and ember-in-viewport are using different versions of intersection-observer-admin (0.2.13 located at /usr/src/fe/node_modules/ember-infinity/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js vs 0.3.0 located at /usr/src/fe/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js)
        at Bundler
-~- created here: -~-
    at new Plugin (/usr/src/fe/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new Bundler (/usr/src/fe/node_modules/ember-auto-import/js/bundler.js:34:9)
    at AutoImport.makeBundler (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:57:16)
    at AutoImport.addTo (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:67:38)
    at EmberApp.host.addonPostprocessTree (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:101:29)
    at EmberApp.toTree (/usr/src/fe/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
    at EmberApp.appInstance.toTree (/usr/src/fe/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/usr/src/fe/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at module.exports (/usr/src/fe/ember-cli-build.js:108:23)
    at Builder.readBuildFile (/usr/src/fe/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/usr/src/fe/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/usr/src/fe/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/usr/src/fe/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/usr/src/fe/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/usr/src/fe/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/usr/src/fe/node_modules/rsvp/dist/rsvp.js:498:33)
    at /usr/src/fe/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/usr/src/fe/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: ember-in-viewport and ember-in-viewport are using different versions of intersection-observer-admin (0.2.13 located at /usr/src/fe/node_modules/ember-infinity/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js vs 0.3.0 located at /usr/src/fe/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js)
        at Bundler
-~- created here: -~-
    at new Plugin (/usr/src/fe/node_modules/ember-auto-import/node_modules/broccoli-plugin/dist/index.js:47:36)
    at new Bundler (/usr/src/fe/node_modules/ember-auto-import/js/bundler.js:34:9)
    at AutoImport.makeBundler (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:57:16)
    at AutoImport.addTo (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:67:38)
    at EmberApp.host.addonPostprocessTree (/usr/src/fe/node_modules/ember-auto-import/js/auto-import.js:101:29)
    at EmberApp.toTree (/usr/src/fe/node_modules/ember-cli/lib/broccoli/ember-app.js:1825:17)
    at EmberApp.appInstance.toTree (/usr/src/fe/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at EmberApp.appInstance.toTree (/usr/src/fe/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at module.exports (/usr/src/fe/ember-cli-build.js:108:23)
    at Builder.readBuildFile (/usr/src/fe/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/usr/src/fe/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/usr/src/fe/node_modules/ember-cli/lib/models/builder.js:32:10)
    at ServeTask.run (/usr/src/fe/node_modules/ember-cli/lib/tasks/serve.js:49:7)
    at Promise.resolve.then (/usr/src/fe/node_modules/ember-cli/lib/models/command.js:239:24)
    at tryCatcher (/usr/src/fe/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/usr/src/fe/node_modules/rsvp/dist/rsvp.js:498:33)
    at /usr/src/fe/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/usr/src/fe/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

-~- (end) -~-
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: Bundler
  - originalErrorMessage: ember-in-viewport and ember-in-viewport are using different versions of intersection-observer-admin (0.2.13 located at /usr/src/fe/node_modules/ember-infinity/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js vs 0.3.0 located at /usr/src/fe/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js)
  - stack: Error: ember-in-viewport and ember-in-viewport are using different versions of intersection-observer-admin (0.2.13 located at /usr/src/fe/node_modules/ember-infinity/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js vs 0.3.0 located at /usr/src/fe/node_modules/intersection-observer-admin/dist/intersection-observer-admin.es5.js)
    at Splitter.<anonymous> (/usr/src/fe/node_modules/ember-auto-import/js/splitter.js:172:23)
    at Generator.next (<anonymous>:null:null)
    at fulfilled (/usr/src/fe/node_modules/ember-auto-import/js/splitter.js:5:58)

**Comment by lucasmerat** [comment]
Also seeing this issue!

**Comment by kevinansfield** [comment]
@snewcomer clearing node modules doesn't help for us, we have the same issue with completely fresh installs. Our app uses `yarn` rather than `npm` which may make a difference?

**Comment by snewcomer** [comment]
@kevinansfield What does `npm ls ember-in-viewport`/`npm ls ember-infinity` show you?  (or maybe `yarn ls...`)

**Comment by kevinansfield** [comment]
```
❯ yarn list ember-in-viewport
yarn list v1.22.5
├─ ember-in-viewport@3.10.2
└─ ember-infinity@2.2.0
   └─ ember-in-viewport@3.7.8
```

```
❯ yarn list ember-infinity
yarn list v1.22.5
└─ ember-infinity@2.2.0
```
